### ISSUE TITLE
Exception on Tab view with floating action button

### ISSUE THREAD

**Issue by ethanlee27** [minaxorg/flutter_intro#20]
hi, 
Thank you for your previous reply, but I found another issue with switching tab by pressing tab or slide.
I want to start intro FAB automatically when tab was switched, so I call Intro.of(context).start() in onWidgetLoad() which in FAB.
Then switching tab by pressing tab or sliding with gesture, I will get some exception.
I am using version 3.2.1 of flutter_intro package.
The below is my sample code, please help me.
Thank you very much.

```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'My App',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
          useMaterial3: true,
        ),
        home: Intro(
          padding: EdgeInsets.zero,
          borderRadius: const BorderRadius.all(Radius.circular(4)),
          maskColor: const Color.fromRGBO(0, 0, 0, .6),
          child: const MyHomePage(title: 'Flutter Demo Home Page'),
        ));
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;
  List tabs = ["Tab1", "Tab2", "Tab3"];
  int _tabIndex = 0;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: tabs.length, vsync: this);

    _tabController.addListener(() {
      var index = _tabController.index;
      switch (index) {
        case 0:
          setState(() {
            _tabIndex = 0;
          });
          break;
        case 1:
          setState(() {
            _tabIndex = 1;
          });
          break;
        case 2:
          setState(() {
            _tabIndex = 2;
          });
          break;
        default:
          break;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: IntroStepBuilder(
          group: 'group0',
          order: 1,
          text: 'Navigation Menu',
          builder: (context, key) => IconButton(
            key: key,
            onPressed: () {
              // Scaffold.of(context).openDrawer();
            },
            icon: const Icon(Icons.menu),
          ),
        ),
        title: const Text("App Name"),
        bottom: TabBar(
          controller: _tabController,
          tabs: tabs.map((e) => Tab(text: e)).toList(),
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: tabs.map((e) {
          return KeepAliveWrapper(
            child: Container(
              alignment: Alignment.center,
              child: Text(e, textScaleFactor: 5),
            ),
          );
        }).toList(),
      ),
      floatingActionButton: _buildFab(),
    );
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  Widget _buildFab() {
    return IntroStepBuilder(
      order: 2,
      group: _getGroupName(),
      text: 'page: $_tabIndex',
      onWidgetLoad: () {
        Intro.of(context).start(group: _getGroupName());
      },
      builder: (context, key) => FloatingActionButton(
          key: key,
          backgroundColor: _getBgColor(),
          onPressed: () {
          },
          child: Icon(_getIconData(), color: Colors.white, size: 25)),
    );
  }

  String _getGroupName() {
    String name = 'group$_tabIndex';
    print('group name:$name');
    return name;
  }

  Color _getBgColor() {
    switch (_tabIndex) {
      case 0:
        return Colors.green;
      case 1:
        return Colors.red;
      case 2:
        return Colors.blue;
      default:
        return Colors.black;
    }
  }

  IconData _getIconData() {
    switch (_tabIndex) {
      case 0:
        return Icons.add;
      case 1:
        return Icons.access_time;
      case 2:
        return Icons.add_a_photo;
      default:
        return Icons.abc_sharp;
    }
  }
}
```

Here is two types exception I got
```
======== Exception caught by widgets library =======================================================
The following FlutterIntroException was thrown building RotationTransition(listenable: AnimationController#1859d(⏭ 1.000; paused)➩CurveTween(curve: Cubic(0.42, 0.00, 1.00, 1.00))➩Tween<double>(0.875 → 1.0)➩1.0➩TrainHoppingAnimation(next: _AnimationSwap<double>(AnimationController#0fe8e(⏭ 1.000; paused)➩Tween<double>(0.75 → 1.0)➩1.0, AnimationController#0fe8e(⏭ 1.000; paused)➩CurveTween(curve: Threshold)➩1.0➪ReverseAnimation)), state: _AnimatedState#8d1a2):
The current context is null, because there is no widget in the tree that matches this global key. Please check whether the key in IntroStepBuilder(group: group2, order: 2) has forgotten to bind. If you are already bound, it means you have encountered a bug, please let me know.

The relevant error-causing widget was: 
  Scaffold Scaffold:file:///C:/Users/EthanLee/AndroidProject/Sarun/flutter/QVPN/lib/main2.dart:86:12
When the exception was thrown, this was the stack: 
#0      Intro._render (package:flutter_intro/flutter_intro.dart:217:7)
#1      Intro.start (package:flutter_intro/flutter_intro.dart:407:5)
#2      _MyHomePageState._buildFab.<anonymous closure> (package:qvpn/main2.dart:133:27)
#3      _IntroStepBuilderState.didUpdateWidget (package:flutter_intro/intro_step_builder.dart:83:28)
#4      StatefulElement.update (package:flutter/src/widgets/framework.dart:5652:55)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#6      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
```

```
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building RotationTransition(listenable: AnimationController#0c617(⏭ 1.000; paused)➩CurveTween(curve: Cubic(0.42, 0.00, 1.00, 1.00))➩Tween<double>(0.875 → 1.0)➩1.0➩TrainHoppingAnimation(next: _AnimationSwap<double>(AnimationController#8b518(⏭ 1.000; paused)➩Tween<double>(0.75 → 1.0)➩1.0, AnimationController#8b518(⏭ 1.000; paused)➩CurveTween(curve: Threshold)➩1.0➪ReverseAnimation)), state: _AnimatedState#bba98):
Null check operator used on a null value

The relevant error-causing widget was: 
  Scaffold Scaffold:file:///C:/Users/EthanLee/AndroidProject/Sarun/flutter/QVPN/lib/main2.dart:86:12
When the exception was thrown, this was the stack: 
#0      _IntroStepBuilderState.didUpdateWidget (package:flutter_intro/intro_step_builder.dart:80:61)
#1      StatefulElement.update (package:flutter/src/widgets/framework.dart:5652:55)
#2      Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#3      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#4      Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
```

**Comment by hellohejinyu** [comment]
https://github.com/minaxorg/flutter_intro/assets/8766034/798ac5e0-7bdb-4c60-9abf-532d5eccebde

Thanks for pointing out my mistake again, please use version `3.2.2`

**Comment by ethanlee27** [comment]
Thank you again for fixing it so quickly.
